# -*- coding: utf-8 -*-
"""course_model(other ver but also good).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CvRPUbhaMDqfKZUE4qPXxBnfDGkvJAjV
"""

# !pip install Sastrawi

import re
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

df = pd.read_csv('courses.csv', names = ['course', 'description', 'tags', 'jml_pendaftar'])

def cleanhtml(raw_html):
    cleantext = re.sub('<.*?>|&([a-z0-9]+|#[0-9]{1,6}|#x[0-9a-f]{1,6});', '', raw_html)
    return cleantext

df['description'] = df['description'].apply(cleanhtml)

df.shape

df.head()

stopword_factory = StopWordRemoverFactory()
stopwords = stopword_factory.get_stop_words()

df['description'] = df['description'].fillna('')
df['tags'] = df['tags'].fillna('')
df['tags'] = df['tags'].str.replace(',', ' ')

df['details'] = df['description'] + ' ' + df['tags']

df.head()

count = CountVectorizer(stop_words=stopwords)
count_matrix = count.fit_transform(df['details'])

print(count_matrix.shape)

cosine_sim = cosine_similarity(count_matrix, count_matrix)

indices = pd.Series(df.index, index=df['course'])

def get_recommendations(course, cosine_sim=cosine_sim):
    idx = indices[course]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]

    course_indices = [i[0] for i in sim_scores]
    course_scores = [i[1] for i in sim_scores]

    recommended_courses = df['course'].iloc[course_indices]

    return list(zip(recommended_courses, course_scores))

# Mencari data dengan keyword tertentu
# search_courses = df[df['course'].str.contains('back', case=False)]
# print(search_courses)

get_recommendations('Memulai Pemrograman Dengan Java')
# print(get_recommendations('Memulai Pemrograman Dengan Java'))
get_recommendations('Belajar Dasar Pemrograman Web')

get_recommendations('Belajar Dasar AI')

get_recommendations('Belajar Membuat Aplikasi Android untuk Pemula')

get_recommendations('Belajar Dasar Git dengan GitHub')

get_recommendations('Memulai Pemrograman dengan Kotlin')

get_recommendations('Belajar Membuat Aplikasi Back-End untuk Pemula')