# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YquvleFPfvn47fXzgHafTpTaLTiFxw72
"""

import pandas as pd
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

df_jobs = pd.read_csv('jobs.csv', names=["vacany name", "vacancy description", "company name", "company description",
                                         "vacany location"])
df_jobs.head()


def remove_html(input):
    regex = r"<.*?>"
    cleantext = re.sub(regex, ' ', input)
    return ' '.join(cleantext.split())


df_jobs['vacancy description'] = df_jobs['vacancy description'].apply(remove_html)
df_jobs['company description'] = df_jobs['company description'].apply(remove_html)
df_jobs['soup'] = df_jobs['vacancy description'] + ' ' + df_jobs['company name'] + ' ' + df_jobs[
    'company description'] + ' ' + df_jobs['vacany location']
df_jobs.head()

stopword_factory = StopWordRemoverFactory()
stopwords = stopword_factory.get_stop_words()
count = CountVectorizer(stop_words=stopwords)
count_matrix = count.fit_transform(df_jobs['vacancy description'])

print(count_matrix.shape)

cosine_sim = cosine_similarity(count_matrix, count_matrix)
indices = pd.Series(df_jobs.index, index=df_jobs['vacany name'])


def get_recommendations(jobs, cosine_sim=cosine_sim):
    idx = indices[jobs]

    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]

    jobs_indices = [i[0] for i in sim_scores]
    jobs_scores = [i[1] for i in sim_scores]

    recommended_jobs = df_jobs['vacany name'].iloc[jobs_indices]

    return list(zip(recommended_jobs, jobs_scores))


# get_recommendations('UI/UX Designer (UI/UX)')
# print(get_recommendations('UI/UX Designer (UI/UX)'))
